name: Setup Node
description: Setup Node.js environment

inputs:
  node-version-file:
    description: Specify Node.js version file such as '.node-version', 'package.json' and so on.
    required: true
  cache-key-prefix:
    description: Specify a cache key prefix that depends on the environment.
    required: true
  no-save-cache:
    description: If true, skips saving the cache. Default is false.
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ${{ inputs.node-version-file }}
        package-manager-cache: false

    - name: Get yarn cache dir (Yarn 1)
      id: yarn-cache
      shell: bash
      run: |
        echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

    # Use restore/save separately so we can control when to save.
    - name: Restore yarn cache
      id: yarn-cache-restore
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ inputs.cache-key-prefix }}-yarn-v1-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-yarn-v1-

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile

    - name: Save yarn cache
      if: steps.yarn-cache-restore.outputs.cache-hit != 'true' && inputs.no-save-cache != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ steps.yarn-cache-restore.outputs.cache-primary-key }}
